#!/bin/bash
# 7/9/26

# script to perform read quality checking

#SBATCH --job-name=readQC
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=30g
#SBATCH --time=8:00:00
#SBATCH --output=/gpfs01/home/mbzlld/code_and_scripts/slurm_out_scripts/slurm-%x-%j.out


# load software
module load fastqc-uoneasy/0.12.1-Java-11

# move to working directory
cd ~/data/paul_dyer

# make a dir for the fastqc output files
mkdir -p fastqc

# run fastqc on all fastq files
fastqc fastqs/*.fq.gz -o fastqc -t 32

# run multiqc to merge the individual reports generated by fastqc
multiqc fastqc -o fastqc/multiqc

# unload software
module unload fastqc-uoneasy/0.12.1-Java-11

