#!/bin/bash
#8/9/26

# script to investigate reads that do not map to the reference genome

# setup env
srun --partition defq --cpus-per-task 8 --mem 20g --time 07:00:00 --pty bash
source $HOME/.bash_profile
cd /gpfs01/home/mbzlld/data/paul_dyer/bams


# extract the unmapped reads and convert back to fastqs
conda activate samtools1.24
for bam in *.bam
do
samtools sort -n -@ 8 $bam |
samtools fastq -n -f 4 \
    -1 ../unmapped_reads/${bam%.*}_unmapped_R1.fastq \
    -2 ../unmapped_reads/${bam%.*}_unmapped_R2.fastq \
    -0 /dev/null \
    -s ../unmapped_reads/${bam%.*}_unmapped_singletons.fastq \
    -
done
conda deactivate

# compress the fastq files
cd ../unmapped_reads
gzip *.fastq

# run QC on the unmapped reads
module load fastqc-uoneasy/0.12.1-Java-11
# make a dir for the fastqc output files
mkdir -p fastqc
# run fastqc on all fastq files
fastqc *.fastq.gz -o fastqc -t 8
# run multiqc to merge the individual reports generated by fastqc
multiqc fastqc -o fastqc/multiqc
module unload fastqc-uoneasy/0.12.1-Java-11


# take only 10,000 reads and convert them to fasta format for blasting
conda activate seqtk
for fastq in *.fastq.gz
do
seqtk sample -s100 $fastq 1000 | seqtk seq -a - > ${fastq%.*.*}.fasta
done
conda deactivate


# blast some of the sequences
conda activate blast
blastn \
-query 119-01_unmapped_R1.fasta \
-db /gpfs01/home/mbzlld/data/databases/nt \
-task blastn-short \
-out 119-01_unmapped_R1_blast_results.txt
conda deactivate



