#!/bin/bash
#8/9/26

# script to investigate reads that do not map to the reference genome

# setup env
srun --partition defq --cpus-per-task 8 --mem 20g --time 03:00:00 --pty bash
source $HOME/.bash_profile
conda activate samtools1.24
module load fastqc-uoneasy/0.12.1-Java-11
cd /gpfs01/home/mbzlld/data/paul_dyer/bams


# extract the unmapped reads and convert back to fastqs
for bam in *.bam
do
samtools sort -n -@ 8 $bam |
samtools fastq -n -f 4 \
    -1 ../unmapped_reads/${bam%.*}_unmapped_R1.fastq \
    -2 ../unmapped_reads/${bam%.*}_unmapped_R2.fastq \
    -0 /dev/null \
    -s ../unmapped_reads/${bam%.*}_unmapped_singletons.fastq \
    -
done

# compress the fastq files
cd ../unmapped_reads
gzip *.fastq

# make a dir for the fastqc output files
mkdir -p fastqc

# run fastqc on all fastq files
fastqc *.fastq.gz -o fastqc -t 8

# run multiqc to merge the individual reports generated by fastqc
multiqc fastqc -o fastqc/multiqc


# convert reads to fasta format
conda deactivate
conda activate seqtk

for fastq in *.fastq.gz
do
seqtk sample -A -s100 $fastq 10000 > ${fastq%.*.*}.fasta
done

seqtk sample -s100 119-01_unmapped_R2.fastq.gz 10000 > 119-01_unmapped_sample_R2.fastq


