<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>
<<include ticks.conf>>

#my-heatmap-colours = yellow,dyellow,orange,dorange,dred,purple,dpurple

<image>
<<include etc/image.conf>>
#file  = circos.png
#radius = 1500p
</image>

karyotype = karyotype.txt
chromosomes_units = 1000000 # Mb 

# for ASM:
chromosomes_color = NW_020311997.1=vvdgreen,NC_038012.1=dyellow,NC_038013.1=vdpurple,NC_038014.1=blue,NC_038015.1=lred

########################################

<ideogram>

show_label       = yes
label_font       = default 
label_radius     = 1r + 120p
label_size       = 40
label_parallel   = yes

<spacing>
default = 0.005r
</spacing>

radius*    = 0.85r
thickness = 40p
fill      = yes


</ideogram>

########################################

<plots>

########################
# gene annotation ring
########################

<plot>
type    = heatmap
file    = ../snp_density/gene_counts_20kb_winds.txt
#color   = spectral-5-div
#color   = spectral-11-div
color   = purples-9-seq
scale_log_base   = 0.6
r1   = 0.96r
r0   = 0.84r
</plot>

###################
### SNP heatmap ###
###################

<plot>
type    = heatmap
#file    = ../snp_density/snp_counts_20kb_winds_venenatum_only.txt
#file = ../snp_density/for_circos_snp_density_20kb_venenatum_only.txt
file = ../snp_density/snp_DENSITY_20kb_winds_venenatum_only.txt
#color   = spectral-11-div
#color   = blues-9-seq
#color = ylorrd-9-seq
# I really like this one
#color = ylorrd-9-seq-3,ylorrd-9-seq-4,ylorrd-9-seq-5,ylorrd-9-seq-6,ylorrd-9-seq-7,ylorrd-9-seq-8,ylorrd-9-seq-9,vdpurple,vvdpurple
color = ylorrd-9-seq-3,ylorrd-9-seq-4,ylorrd-9-seq-5,ylorrd-9-seq-6,ylorrd-9-seq-7,ylorrd-9-seq-8,ylorrd-9-seq-9
#color = yellow,dyellow,orange,dorange,red,dpurple,vdpurple
#scale_log_base = 0.45
scale_log_base = 0.7
r1      = 0.82r
r0      = 0.70r
</plot>

#####################
### INDEL heatmap ###
#####################

<plot>
type    = heatmap
file = ../snp_density/indel_DENSITY_20kb_winds_venenatum_only.txt
#color = ylorrd-9-seq
color = ylorrd-9-seq-3,ylorrd-9-seq-4,ylorrd-9-seq-5,ylorrd-9-seq-6,ylorrd-9-seq-7,ylorrd-9-seq-8,ylorrd-9-seq-9
scale_log_base = 0.7
r1      = 0.68r
r0      = 0.56r
</plot>

#################################
### GC CONTENT ANNOTAION RING ###
#################################

<plot>
type  = histogram
file  = gc_dev.txt
r1    = 0.54r
r0    = 0.42r
fill_color = grey
thickness  = 1
extend_bin = no

<rules>
<rule>
condition  = var(value) > 0
fill_color = lgreen
</rule>
<rule>
condition  = var(value) < 0
fill_color = vdgreen
</rule>
</rules>


</plot>



</plots>
